language: python
install:
- pip install hererocks
- hererocks lua53 -l5.3 -rlatest
- source lua53/bin/activate
- lua -v
- luarocks install luacheck
- luarocks install busted
- luarocks install luacov
script:
- luacheck modules/*.lua tests/*.lua
- busted --verbose --coverage tests/*.lua
after_success:
- luacov ^./modules/
- bash <(curl -s https://codecov.io/bash)
